# -*- coding: utf-8 -*-
"""Working With Data & Code A1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YQr56ffvgIzOAJuBo4ntXZe4EoEDwRIN
"""

import matplotlib.pyplot as plt

# Dataset: Taylor Swift songs, albums, and release years
songs = {
    "Tim McGraw": {"album": "Debut", "year": 2006},
    "Picture to Burn": {"album": "Debut", "year": 2006},
    "Teardrops on My Guitar": {"album": "Debut", "year": 2006},
    "A Place in This World": {"album": "Debut", "year": 2006},
    "Cold as You": {"album": "Debut", "year": 2006},
    "The Outside": {"album": "Debut", "year": 2006},
    "Tied Together with a Smile": {"album": "Debut", "year": 2006},
    "Stay Beautiful": {"album": "Debut", "year": 2006},
    "Should've Said No": {"album": "Debut", "year": 2006},
    "Mary's Song": {"album": "Debut", "year": 2006},
    "Our Song": {"album": "Debut", "year": 2006},
    "I'm Only Me When I'm With You": {"album": "Debut", "year": 2006},
    "Invisible": {"album": "Debut", "year": 2006},
    "A Perfectly Good Heart": {"album": "Debut", "year": 2006},
    "Fearless": {"album": "Fearless", "year": 2008},
    "Fifteen": {"album": "Fearless", "year": 2008},
    "Love Story": {"album": "Fearless", "year": 2008},
    "Hey Stephen": {"album": "Fearless", "year": 2008},
    "White Horse": {"album": "Fearless", "year": 2008},
    "You Belong with Me": {"album": "Fearless", "year": 2008},
    "Breathe": {"album": "Fearless", "year": 2008},
    "Tell Me Why": {"album": "Fearless", "year": 2008},
    "You're Not Sorry": {"album": "Fearless", "year": 2008},
    "The Way I Loved You": {"album": "Fearless", "year": 2008},
    "Forever & Always": {"album": "Fearless", "year": 2008},
    "The Best Day": {"album": "Fearless", "year": 2008},
    "Change": {"album": "Fearless", "year": 2008},
    "Jump Then Fall": {"album": "Fearless", "year": 2008},
    "Untouchable": {"album": "Fearless", "year": 2008},
    "Come In With The Rain": {"album": "Fearless", "year": 2008},
    "Superstar": {"album": "Fearless", "year": 2008},
    "The Other Side Of The Door": {"album": "Fearless", "year": 2008},
    "Today Was A Fairytale": {"album": "Fearless", "year": 2008},
    "You All Over Me": {"album": "Fearless", "year": 2008},
    "Mr. Perfectly Fine": {"album": "Fearless", "year": 2008},
    "We Were Happy": {"album": "Fearless", "year": 2008},
    "That's When": {"album": "Fearless", "year": 2008},
    "Don't You": {"album": "Fearless", "year": 2008},
    "Bye Bye Baby": {"album": "Fearless", "year": 2008},
    "Mine": {"album": "Speak Now", "year": 2010},
    "Sparks Fly": {"album": "Speak Now", "year": 2010},
    "Back To December": {"album": "Speak Now", "year": 2010},
    "Speak Now": {"album": "Speak Now", "year": 2010},
    "Dear John": {"album": "Speak Now", "year": 2010},
    "Mean": {"album": "Speak Now", "year": 2010},
    "The Story Of Us": {"album": "Speak Now", "year": 2010},
    "Never Grow Up": {"album": "Speak Now", "year": 2010},
    "Enchanted": {"album": "Speak Now", "year": 2010},
    "Better Than Revenge": {"album": "Speak Now", "year": 2010},
    "Innocent": {"album": "Speak Now", "year": 2010},
    "Haunted": {"album": "Speak Now", "year": 2010},
    "Last Kiss": {"album": "Speak Now", "year": 2010},
    "Long Live": {"album": "Speak Now", "year": 2010},
    "State Of Grace": {"album": "Red", "year": 2012},
    "Red": {"album": "Red", "year": 2012},
    "Treacherous": {"album": "Red", "year": 2012},
    "I Knew You Were Trouble": {"album": "Red", "year": 2012},
    "All Too Well": {"album": "Red", "year": 2012},
    "22": {"album": "Red", "year": 2012},
    "I Almost Do": {"album": "Red", "year": 2012},
    "We Are Never Getting Back Together": {"album": "Red", "year": 2012},
    "Stay Stay Stay": {"album": "Red", "year": 2012},
    "The Last Time": {"album": "Red", "year": 2012},
    "Holy Ground": {"album": "Red", "year": 2012},
    "Sad Beautiful Tragic": {"album": "Red", "year": 2012},
    "The Lucky One": {"album": "Red", "year": 2012},
    "Everything Has Changed": {"album": "Red", "year": 2012},
    "Starlight": {"album": "Red", "year": 2012},
    "Begin Again": {"album": "Red", "year": 2012},
    "The Moment I Knew": {"album": "Red", "year": 2012},
    "Come Back...Be Here": {"album": "Red", "year": 2012},
    "Girl At Home": {"album": "Red", "year": 2012},
    "Welcome To New York": {"album": "1989", "year": 2014},
    "Blank Space": {"album": "1989", "year": 2014},
    "Style": {"album": "1989", "year": 2014},
    "Out Of The Woods": {"album": "1989", "year": 2014},
    "All You Had To Do Was Stay": {"album": "1989", "year": 2014},
    "Shake It Off": {"album": "1989", "year": 2014},
    "I Wish I Would": {"album": "1989", "year": 2014},
    "Bad Blood": {"album": "1989", "year": 2014},
    "Wildest Dreams": {"album": "1989", "year": 2014},
    "How You Get The Girl": {"album": "1989", "year": 2014},
    "This Love": {"album": "1989", "year": 2014},
    "I Know Places": {"album": "1989", "year": 2014},
    "Clean": {"album": "1989", "year": 2014},
    "Wonderland": {"album": "1989", "year": 2014},
    "You Are In Love": {"album": "1989", "year": 2014},
    "New Romantics": {"album": "1989", "year": 2014},
    "Ready For It": {"album": "Reputation", "year": 2017},
    "End Game": {"album": "Reputation", "year": 2017},
    "I Did Something": {"album": "Reputation", "year": 2017},
    "Don't Blame Me": {"album": "Reputation", "year": 2017},
    "Delicate": {"album": "Reputation", "year": 2017},
    "Look What You Made Me Do": {"album": "Reputation", "year": 2017},
    "So It Goes...": {"album": "Reputation", "year": 2017},
    "Gorgeous": {"album": "Reputation", "year": 2017},
    "Getaway Car": {"album": "Reputation", "year": 2017},
    "King Of My Heart": {"album": "Reputation", "year": 2017},
    "Dancing With Our Hands Tied": {"album": "Reputation", "year": 2017},
    "Dress": {"album": "Reputation", "year": 2017},
    "This Is Why We Cant Have Nice Things": {"album": "Reputation", "year": 2017},
    "Call It What You Want": {"album": "Reputation", "year": 2017},
    "New Years Day": {"album": "Reputation", "year": 2017},
    "I Forgot That You Existed": {"album": "Lover", "year": 2019},
    "Cruel Summer": {"album": "Lover", "year": 2019},
    "Lover": {"album": "Lover", "year": 2019},
    "The Man": {"album": "Lover", "year": 2019},
    "The Archer": {"album": "Lover", "year": 2019},
    "I Think He Knows": {"album": "Lover", "year": 2019},
    "Miss Americana & The Heartbreak Prince": {"album": "Lover", "year": 2019},
    "Paper Rings": {"album": "Lover", "year": 2019},
    "Cornelia Street": {"album": "Lover", "year": 2019},
    "Death By A Thousand Cuts": {"album": "Lover", "year": 2019},
    "London Boy": {"album": "Lover", "year": 2019},
    "Soon You'll Get Better": {"album": "Lover", "year": 2019},
    "False God": {"album": "Lover", "year": 2019},
    "You Need To Calm Down": {"album": "Lover", "year": 2019},
    "Aferglow": {"album": "Lover", "year": 2019},
    "ME!": {"album": "Lover", "year": 2019},
    "It's Nice To Have A Friend": {"album": "Lover", "year": 2019},
    "Daylight": {"album": "Lover", "year": 2019},
    "The 1": {"album": "Folklore", "year": 2020},
    "Cardigan": {"album": "Folklore", "year": 2020},
    "The Last Great American Dynasty": {"album": "Folklore", "year": 2020},
    "Exile": {"album": "Folklore", "year": 2020},
    "My Tears Ricochet": {"album": "Folklore", "year": 2020},
    "Mirrorball": {"album": "Folklore", "year": 2020},
    "Seven": {"album": "Folklore", "year": 2020},
    "August": {"album": "Folklore", "year": 2020},
    "This Is Me Trying": {"album": "Folklore", "year": 2020},
    "Illicit Affairs": {"album": "Folklore", "year": 2020},
    "Invisible String": {"album": "Folklore", "year": 2020},
    "Mad Woman": {"album": "Folklore", "year": 2020},
    "Epiphany": {"album": "Folklore", "year": 2020},
    "Betty": {"album": "Folklore", "year": 2020},
    "Peace": {"album": "Folklore", "year": 2020},
    "Hoax": {"album": "Folklore", "year": 2020},
    "Willow": {"album": "Evermore", "year": 2020},
    "Champagne Problems": {"album": "Evermore", "year": 2020},
    "Gold Rush": {"album": "Evermore", "year": 2020},
    "'Tis The Damn Season": {"album": "Evermore", "year": 2020},
    "Tolerate It": {"album": "Evermore", "year": 2020},
    "No Body, No Crime": {"album": "Evermore", "year": 2020},
    "Happiness": {"album": "Evermore", "year": 2020},
    "Dorothea": {"album": "Evermore", "year": 2020},
    "Coney Island": {"album": "Evermore", "year": 2020},
    "Ivy": {"album": "Evermore", "year": 2020},
    "Cowboy Like Me": {"album": "Evermore", "year": 2020},
    "Long Story Short": {"album": "Evermore", "year": 2020},
    "Marjorie": {"album": "Evermore", "year": 2020},
    "Closure": {"album": "Evermore", "year": 2020},
    "Evermore": {"album": "Evermore", "year": 2020},
    "Lavender Haze": {"album": "Midnights", "year": 2022},
    "Maroon": {"album": "Midnights", "year": 2022},
    "Anti-Hero": {"album": "Midnights", "year": 2022},
    "Snow On The Beach": {"album": "Midnights", "year": 2022},
    "You're On Your Own, Kid": {"album": "Midnights", "year": 2022},
    "Midnight Rain": {"album": "Midnights", "year": 2022},
    "Question...?": {"album": "Midnights", "year": 2022},
    "Vigilante Shit": {"album": "Midnights", "year": 2022},
    "Bejeweled": {"album": "Midnights", "year": 2022},
    "Labyrinth": {"album": "Midnights", "year": 2022},
    "Karma": {"album": "Midnights", "year": 2022},
    "Sweet Nothing": {"album": "Midnights", "year": 2022},
    "Mastermind": {"album": "Midnights", "year": 2022},

}

def count_word_occurrences(word, song_titles):
    count = 0
    for title in song_titles:
        if word.lower() in title.lower():
            count += 1
    return count

def list_albums():
    albums = list(set(song["album"] for song in songs.values()))
    return albums

def list_songs_in_album(album_name):
    album_songs = [title for title, song in songs.items() if song["album"].lower() == album_name.lower()]
    return album_songs

def main():
    print("Welcome to the Taylor Swift Song Analyser!")
    print("Please enter a word to count occurrences in song titles:")
    target_word = input()

    word_count = count_word_occurrences(target_word, songs.keys())
    print(f"The word '{target_word}' appears in {word_count} song titles.")

    # Listing albums in order of release year
    albums = list_albums()
    albums.sort(key=lambda album: min(song["year"] for title, song in songs.items() if song["album"].lower() == album.lower()))

    print("\nList of albums (in order of release year):")
    for album in albums:
        print(album)

    print("\nEnter an album name to list songs in that album (or 'all' for all songs):")
    album_choice = input()

    if album_choice.lower() == "all":
        for title, song in songs.items():
            print(f"Title: {title}, Album: {song['album']}, Year: {song['year']}")
    else:
        album_songs = list_songs_in_album(album_choice)
        if album_songs:
            print(f"\nSongs in '{album_choice}':")
            for song_title in album_songs:
                print(song_title)
        else:
            print("Album not found.")

    # Creating a bar chart to visualize song release years
    release_years = [song["year"] for song in songs.values()]
    unique_years = list(set(release_years))
    year_counts = [release_years.count(year) for year in unique_years]

    plt.bar(unique_years, year_counts, color='pink')
    plt.xlabel('Release Year')
    plt.ylabel('Number of Songs')
    plt.title('Taylor Swift Songs Release Years')
    plt.show()

if __name__ == "__main__":
    main()